import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/redux/provider/Provider";
import ReactQueryProvider from "@/api/reactQueryProvider/ReactQueryProvider";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Patient Module",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <ToastContainer />

        <ReactQueryProvider>
          <Providers>
            {children}

          </Providers>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
